AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  blog-aws-lambda

  Sample SAM Template for blog-aws-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        AWS_ID: !Ref AWSID
        AWS_SECRET: !Ref AWSSecret
        AWS_BUCKET: !Ref AWSBucket

Resources:
  BlogFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ../src/
      Handler: ArticleServer.get_response
      Runtime: python3.12
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED

Parameters:
  AWSID:
    Type: String
    Description: Environment variable value for AWS_ID
  AWSSecret:
    Type: String
    Description: Environment variable value for AWS_SECRET
  AWSBucket:
    Type: String
    Description: Environment variable value for AWS_BUCKET

Outputs:
  BlogFunction:
    Description: Blog Lambda Function ARN
    Value: !GetAtt BlogFunction.Arn
  BlogFunctionIamRole:
    Description: Implicit IAM Role created for Blog Lambda function
    Value: !GetAtt BlogFunctionRole.Arn
  BlogFunctionUrlEndpoint:
    Description: Blog Lambda Function URL Endpoint
    Value: !GetAtt BlogFunctionUrl.FunctionUrl